"""Initial migration

Revision ID: 7a0af789b13f
Revises: 844c2e079a61
Create Date: 2023-05-26 12:44:00.820305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0af789b13f'
down_revision = '844c2e079a61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
