"""Add new fields to Book model

Revision ID: 844c2e079a61
Revises: 
Create Date: 2023-05-26 07:46:47.438583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844c2e079a61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_date', sa.String(length=300), nullable=True))
    op.add_column('books', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'price')
    op.drop_column('books', 'publication_date')
    # ### end Alembic commands ###
